# -*- coding: utf-8 -*-
"""2o trabalho de fia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh8KXncsZ80wI7WNhDzR7LiJlAoN_sOx
"""

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from tensorflow import keras # Import Keras from TensorFlow
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import regularizers

print(f'Python: {sys.version.split()[0]}')
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')
print(f'Seaborn: {sns.__version__}')
print(f'Keras: {keras.__version__}') # Print Keras version using the imported name

# --- 1. CARREGAMENTO E LIMPEZA DOS DADOS ---
print("\n--- 1. Carregamento e Limpeza ---")
# OBS: O nome do arquivo foi ajustado para 'heart.csv' para compatibilidade com pd.read_csv
try:
    df = pd.read_csv('../content/heart.csv')
except FileNotFoundError:
    print("ERRO: Certifique-se de que o arquivo 'heart.csv' está no diretório correto.")
    sys.exit()

print(f"Shape Inicial: {df.shape}")

# Remoção de valores ausentes ('?') e NaN
df = df[~df.isin(['?'])]
df = df.dropna(axis=0)
print(f"Shape após limpeza: {df.shape}")

# Conversão de todas as colunas para numérico
df = df.apply(pd.to_numeric)
print("Tipos de Dados convertidos para numérico.")

# --- 2. ANÁLISE EXPLORATÓRIA DE DADOS (AED) ---
print("\n--- 2. Análise Exploratória e Visualização ---")
print(df.describe())

# Mapa de Calor da Correlação
plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Mapa de Calor da Correlação entre Atributos')
plt.show()

# --- 3. PRÉ-PROCESSAMENTO E DIVISÃO (Foco Binário) ---

# Variável Alvo: 0 (Ausência) ou 1 (Presença) de doença cardíaca [cite: 11, 16]
# O conjunto de dados Heart Disease UCI já utiliza 0/1 para este fim[cite: 11, 16].
# Se o dataset incluir classes 2, 3, 4, a conversão é feita abaixo para garantir o modelo binário.
y = df['target'].copy()
X = df.drop('target', axis=1).copy()

# Garante que 'target' é estritamente binário (0 ou 1)
y[y > 0] = 1

# Divisão dos dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"\nDados Treino: {X_train.shape}, Dados Teste: {X_test.shape}")

# Padronização de Características (StandardScaler)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Dados Padronizados (StandardScaler).")


# --- 4. CONSTRUÇÃO E TREINAMENTO DO MODELO BINÁRIO ---

def create_binary_model(input_dim):
    # Modelo ANN feedforward com 2-3 camadas ocultas [cite: 32]
    model = Sequential()

    # 1ª Camada Oculta: 16 neurônios, ReLU [cite: 32]
    model.add(Dense(16, input_dim=input_dim, activation='relu',
                    kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.25)) # Regularização (Dropout) [cite: 27]

    # 2ª Camada Oculta: 8 neurônios, ReLU
    model.add(Dense(8, activation='relu',
                    kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.25))

    # Camada de Saída: 1 neurônio, Sigmoide para classificação binária [cite: 31]
    model.add(Dense(1, activation='sigmoid'))

    # Compilação
    model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
    return model

# Criação do modelo
binary_model = create_binary_model(X_train_scaled.shape[1])
print("\n--- 4. Sumário do Modelo Binário ---")
binary_model.summary()

# Treinamento do modelo
history = binary_model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=50,
    batch_size=10,
    verbose=0 # Mantenha 1 para ver o progresso
)
print("Treinamento concluído.")

# --- 5. AVALIAÇÃO E MÉTRICAS FINAIS ---

# 5.1 Gráficos de Acurácia e Perda
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Treino')
plt.plot(history.history['val_accuracy'], label='Teste')
plt.title('Acurácia do Modelo')
plt.ylabel('Acurácia')
plt.xlabel('Época')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Treino')
plt.plot(history.history['val_loss'], label='Teste')
plt.title('Perda (Loss) do Modelo')
plt.ylabel('Perda')
plt.xlabel('Época')
plt.legend()
plt.show()

# 5.2 Geração de Previsões
y_pred_prob = binary_model.predict(X_test_scaled)
y_pred_binary = np.round(y_pred_prob).astype(int)

# 5.3 Relatório de Classificação e Acurácia
print("\n--- 5. Resultados Finais e Métricas (Conjunto de Teste) ---")
print(f"Acurácia: {accuracy_score(y_test, y_pred_binary):.4f}")
print("\nRelatório de Classificação (Precisão, Recall, F1-Score):\n")
print(classification_report(y_test, y_pred_binary, target_names=['0 (Sem Doença)', '1 (Com Doença)']))

# 5.4 Matriz de Confusão
cm = confusion_matrix(y_test, y_pred_binary)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Prev. 0', 'Prev. 1'],
            yticklabels=['Real 0', 'Real 1'])
plt.title('Matriz de Confusão')
plt.ylabel('Real')
plt.xlabel('Previsto')
plt.show()

"""# Nova seção"""